### ISSUE TITLE
Question on step 2 of README

### ISSUE THREAD

**Issue by stevevu** [cjkoepke/wp-tailwind#13]
Hi, 

Thanks for this contribution.

What is meant by Step 2 of the How to Get Started section of the README file:

**2. Run a find/replace for the following strings:
wp-tailwind
WP_Tailwind
wp_tailwind_**

thanks,
Steve

**Comment by cjkoepke** [comment]
@stevevu Usually in your code editor, you can do a project search/replace operation. The following strings are contextual and are:

1. Textdomain
2. Namespace
3. Function prefix

**Comment by stevevu** [comment]
Thanks for the speedy reply!

I guess what I really meant to ask is do we need to even replace these wp tailwind prefixes?  They seem pretty good and unlikely to be used by anywhere else?

thanks,
Steve

**Comment by cjkoepke** [comment]
@stevevu Oh certainly, they are not required to replace — it's just best practice :)
