### ISSUE TITLE
"min" prefix 404 on "npm start"

### ISSUE THREAD

**Issue by markjohnson4** [cjkoepke/wp-tailwind#15]
After I ran "npm start", the project seems to work except it references "main.min.css" and "main.min.js" in wp_enqueue_scripts while actually generating files named "main.css" and "main.js" (without the "min").  

# Quick Fix until more permanent solution added

in "enqueue.php"...

change
$min_ext = ( defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG ) ? '' : '.min';
to 
$min_ext = '';

**Comment by cjkoepke** [comment]
@markjohnson4 This is controlled by your build command. So if you are on production (and `SCRIPT_DEBUG` is therefore `false`), you should run `npm run prod`. Otherwise, if you have `SCRIPT_DEBUG` set to `true`, then run `npm run dev`.
