### ISSUE TITLE
Call to undefined function A7\autoload()

### ISSUE THREAD

**Issue by lexxyungcarter** [cjkoepke/wp-tailwind#2]
Hi. I am really interested in seeing this at work. 
However, I am getting the error below.

Fatal error: Uncaught Error: Call to undefined function A7\autoload() in /wp-content/themes/wp-tailwind/functions.php:13

Any thoughts on this?

**Comment by giauna** [comment]
Same problem..
Stupid (= not the best) solution, try to modify functions.php :

```
<?php
/**
 * Kickoff theme setup and build
 */

namespace WP_Tailwind;

define( 'WP_Tailwind_VERSION', wp_get_theme()->version );
define( 'WP_Tailwind_DIR', __DIR__ );
define( 'WP_Tailwind_URL', get_template_directory_uri() );
/*
try {
	\A7\autoload( __DIR__ . '/src' );
} catch ( \Exception $e ) {
	echo $e->getMessage();
	die;
}
*/
require_once( __DIR__ . '/src/classes.php');
require_once( __DIR__ . '/src/enqueue.php');
require_once( __DIR__ . '/src/setup.php');
require_once( __DIR__ . '/src/sidebars.php');
```

**Comment by cjkoepke** [comment]
Sorry, everyone, didn't see these comments and my alerts were turned off. I see what's going on here — will update a patch soon, but this assumes a project dependency that doesn't exist inside the theme.

**Comment by cjkoepke** [comment]
This should be fixed now. Update the theme to the latest version of `master` and run `composer install` to get the required Composer dependencies.

Related commit: https://github.com/cjkoepke/wp-tailwind/commit/e602c13e05d928b437d343e57d827d84a7d5c5fd
